const countries = {
  'Afghan': 'af',
  'Albanian' : 'al',
  'Algerian' : 'dz',
  'Andorran' : 'ad',
  'Angolan' : 'ao',
  'Antiguans' : 'ag',
  'Argentine' : 'ar',
  'Armenian' : 'am',
  'Australian' : 'au',
  'Austrian' : 'at',
  'Azerbaijani' : 'az',
  'Bahamian' : 'bs',
  'Bahraini' : 'bh',
  'Bangladeshi' : 'bd',
  'Barbadian' : 'bb',
  'Belarusian' : 'by',
  'Belgian' : 'be',
  'Belizean' : 'bz',
  'Beninese' : 'bj',
  'Bhutanese' : 'bt',
  'Bolivian' : 'bo',
  'Bosnian' : 'ba',
  'Brazilian' : 'br',
  'Bulgarian' : 'bg',
  'Burkinabe' : 'bf',
  'Burmese' : 'mm',
  'Burundian' : 'bi',
  'Cabo Verdean' : 'cv',
  'Cambodian' : 'kh',
  'Cameroonian' : 'cm',
  'Canadian' : 'ca',
  'Central African' : 'cf',
  'Chadian' : 'td',
  'Chilean' : 'cl',
  'Chinese' : 'cn',
  'Colombian' : 'co',
  'Comoran' : 'km',
  'Congolese' : 'cg',
  'Costa Rican' : 'cr',
  'Croatian' : 'hr',
  'Cuban' : 'cu',
  'Cypriot' : 'cy',
  'Czech' : 'cz',
  'Danish' : 'dk',
  'Djiboutian' : 'dj',
  'Dominican' : 'do',
  'Dutch' : 'nl',
  'East Timorese' : 'tl',
  'Ecuadorean' : 'ec',
  'Egyptian' : 'eg',
  'Emirati' : 'ae',
  'Equatorial Guinean' : 'gq',
  'Eritrean' : 'er',
  'Estonian' : 'ee',
  'Ethiopian' : 'et',
  'Fijian' : 'fj',
  'Finnish' : 'fi',
  'French' : 'fr',
  'Gabonese' : 'ga',
  'Gambian' : 'gm',
  'Georgian' : 'ge',
  'German' : 'de',
  'Ghanaian' : 'gh',
  'Greek' : 'gr',
  'Grenadian' : 'gd',
  'Guatemalan' : 'gt',
  'Guinean' : 'gn',
  'Guyanese' : 'gy',
  'Haitian' : 'ht',
  'Honduran' : 'hn',
  'Hungarian' : 'hu',
  'Icelandic' : 'is',
  'Indian' : 'in',
  'Indonesian' : 'id',
  'Iranian' : 'ir',
  'Iraqi' : 'iq',
  'Irish' : 'ie',
  'Israeli' : 'il',
  'Italian' : 'it',
  'Jamaican' : 'jm',
  'Japanese' : 'jp',
  'Jordanian' : 'jo',
  'Kazakhstani' : 'kz',
  'Kenyan' : 'ke',
  'Kiribati' : 'ki',
  'Korean' : 'kr',
  'Kuwaiti' : 'kw',
  'Kyrgyzstani' : 'kg',
  'Laotian' : 'la',
  'Latvian' : 'lv',
  'Lebanese' : 'lb',
  'Lesotho' : 'ls',
  'Liberian' : 'lr',
  'Libyan' : 'ly',
  'Liechtensteiner' : 'li',
  'Lithuanian' : 'lt',
  'Luxembourger' : 'lu',
  'Madagascan' : 'mg',
  'Malawian' : 'mw',
  'Malaysian' : 'my',
  'Maldivian' : 'mv',
  'Malian' : 'ml',
  'Maltese' : 'mt',
  'Marshallese' : 'mh',
  'Mauritian' : 'mu',
  'Mexican' : 'mx',
  'Micronesian' : 'fm',
  'Moldovan' : 'md',
  'Monacan' : 'mc',
  'Monegasque' : 'mc',
  'Mongolian' : 'mn',
  'Montenegrin' : 'me',
  'Moroccan' : 'ma',
  'Mozambican' : 'mz',
  'Namibian' : 'na',
  'Nauruan' : 'nr',
  'Nepalese' : 'np',
  'New Zealander' : 'nz',
  'Nicaraguan' : 'ni',
  'Nigerien' : 'ne',
  'Nigerian' : 'ng',
  'North Korean' : 'kp',
  'Norwegian' : 'no',
  'Omani' : 'om',
  'Pakistani' : 'pk',
  'Palauan' : 'pw',
  'Panamanian' : 'pa',
  'Papua New Guinean' : 'pg',
  'Paraguayan' : 'py',
  'Peruvian' : 'pe',
  'Philippine' : 'ph',
  'Polish' : 'pl',
  'Portuguese' : 'pt',
  'Qatari' : 'qa',
  'Romanian' : 'ro',
  'Russian' : 'ru',
  'Rwandan' : 'rw',
  'Saint Kitts and Nevis' : 'kn',
  'Saint Lucian' : 'lc',
  'Saint Vincentian' : 'vc',
  'Salvadoran' : 'sv',
  'Samoan' : 'ws',
  'San Marinese' : 'sm',
  'Sao Tomean' : 'st',
  'Saudi' : 'sa',
  'Scottish' : 'gb',
  'Senegalese' : 'sn',
  'Serbian' : 'rs',
  'Seychellois' : 'sc',
  'Sierra Leonean' : 'sl',
  'Singaporean' : 'sg',
  'Slovak' : 'sk',
  'Slovenian' : 'si',
  'Somali' : 'so',
  'South African' : 'za',
  'South Sudanese' : 'ss',
  'Spanish' : 'es',
  'Sri Lankan' : 'lk',
  'Sudanese' : 'sd',
  'Surinamese' : 'sr',
  'Swedish' : 'se',
  'Swiss' : 'ch',
  'Syrian' : 'sy',
  'Taiwanese' : 'tw',
  'Tajikistani' : 'tj',
  'Tanzanian' : 'tz',
  'Thai' : 'th',
  'Togolese' : 'tg',
  'Tongan' : 'to',
  'Trinidadian' : 'tt',
  'Tunisian' : 'tn',
  'Turkish' : 'tr',
  'Turkmen' : 'tm',
  'Tuvaluan' : 'tv',
  'Ugandan' : 'ug',
  'Ukrainian' : 'ua',
  'United Arab Emirates' : 'ae',
  'British' : 'gb-eng',
  'United States' : 'us',
  'American' : 'us',
  'Uruguayan' : 'uy',
  'Uzbekistani' : 'uz',
  'Vanuatuan' : 'vu',
  'Vatican' : 'va',
  'Venezuelan' : 've',
  'Vietnamese' : 'vn',
  'Yemeni' : 'ye',
  'Zambian' : 'zm',
  'Zimbabwean' : 'zw'
};
